services:
  ctcf-predictor:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ctcf-predictor:latest
    network_mode: host
    environment:
      - https_proxy=http://10.6.254.210:3128
      - http_proxy=http://10.6.254.210:3128
      - HTTP_PROXY=http://10.6.254.210:3128
      - HTTPS_PROXY=http://10.6.254.210:3128
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: ["/bin/bash"]
    tty: true
    stdin_open: true
